### ISSUE TITLE
OLED display graphics library

### ISSUE THREAD

**Issue by kammce** [kammce/SJSU-Dev2#28]
May just pull in the Adafruit libraries if their licenses are compatible.

**Comment by rehanashraf** [comment]
Do we a OLED display in mind which we are going to use. Not so sure how does these libraries look like. Are they generic for all displays?

**Comment by jbajaj12** [comment]
https://github.com/kammce/SJSU-Dev2/blob/master/datasheets/OLED-Display/ER-OLED0.96-1_Series_Datasheet.pdf

**Comment by kammce** [comment]
https://www.amazon.com/HiLetgo-128x64-SSH1106-Display-Arduino/dp/B01N1LZT8L

**Comment by kammce** [comment]
Resolved by PR: #261 & #265
