### ISSUE TITLE
Queue.h has a dependency on FreeRTOS.h 

### ISSUE THREAD

**Issue by rabeelio** [kammce/SJSU-Dev2#342]
Tried including rtos.hpp but lint was complaining about the order. The problem is that queue.h throws a compile time error if it detects that FreeRTOS.h didn't come first.

The current work around is to just include FreeRTOS.h and then queue.h. See can.hpp.

`Executing 'lint' check /home/rabeel/SJ2_DEV/SJSU-Dev2/firmware/library/L1_Drivers/can.hpp:4: Found C system header after other header. Should be: can.h, c system, c++ system, other. [build/include_order] [4]`

**Comment by kammce** [comment]
Resolved by #361.
