### ISSUE TITLE
CAN Driver: Send() should be able to send 1 time messages

### ISSUE THREAD

**Issue by rabeelio** [kammce/SJSU-Dev2#344]
If the Send() function gets a pointer that only has scope within a
  function call, then once that function goes out of scope, the pointer will
  become a dangling pointer (pointer to invalid data). Afterwards, when
  WriteMessageToBuffer() tries to access the data to write it to the HW
  buffers, it will get corrupt data. This problem can arise if the user wants
  to send a 1 time message. However, if the user is sending cyclic messages,
  it is assumed that global message handles exist somewhere in the user's app
  layer since they need to be updated periodically.

**Comment by kammce** [comment]
Resolved by #1118.
