### ISSUE TITLE
CAN Driver: calculate baud rates using peripheral frequency

### ISSUE THREAD

**Issue by rabeelio** [kammce/SJSU-Dev2#347]
Add details about how the baud rate is calculated in documentation.

**Comment by rabeelio** [comment]
@kammce what do you mean by "baud rates are calculation details"?

**Comment by kammce** [comment]
Hmmm, that seems poorly written by my part. I just mean that there should be some documentation, comment, to how you are calculating the baud rate since, if I remember right, it isn't as straight forward as:

`divider = peripheral_clock / baud_rate`
