### ISSUE TITLE
SD Card Driver: Simplify Function Implementation with Memory Block Class

### ISSUE THREAD

**Issue by rjavier441** [kammce/SJSU-Dev2#348]
At its current state, the Sd Card Driver is not terribly easy to use with arrays of blocks. It imposes a lot of extra work on the user to make sure their block constructs are of the correct block size. This could be simplified with the addition of a designated MemoryBlock class that can be used to represent individual blocks of SD Card Memory.

**Comment by kammce** [comment]
I would actually consider using a structure rather than a class. Semantically structs are more for being data structures rather than objects with a suit of methods they can perform.
