### ISSUE TITLE
Fake queue.h functions in rtos.hpp 

### ISSUE THREAD

**Issue by rabeelio** [kammce/SJSU-Dev2#357]
When running can_test.hpp, I get undefined references to queue.h functions that I'm using in can.hpp. C functions cannot be mocked with the FakeIt framework since it requires an interface in order for functions to be mocked. However, we have another framework, as part of the test suite, called FFF that allows us to fake out these functions and use them with the FakeIt framework. 

This may depend on https://github.com/kammce/SJSU-Dev2/issues/342 being resolved first.

**Comment by kammce** [comment]
Resolved by #361.
