### ISSUE TITLE
Discrepancy between time units

### ISSUE THREAD

**Issue by harmandersihra** [kammce/SJSU-Dev2#392]
https://github.com/kammce/SJSU-Dev2/blob/3acc8e268ac9e30259a7da7aa33fbb7db4dabecc/firmware/library/utility/time.hpp#L23-L33

Uptime() supposedly returns time in nanoseconds, but Milliseconds returns milliseconds by dividing nanoseconds by 1,000 when it should be by 1,000,000. Uptime() seems like it's actually returning microseconds and not nanoseconds.

**Comment by kammce** [comment]
Whoops. That should be changed. At the moment, we are only getting the time in microseconds. So we should change the API to state that the time in microseconds and not nanoseconds.

**Comment by kammce** [comment]
@harmandersihra can you make that change and create a PR.

**Comment by kammce** [comment]
Resolved by #393
