### ISSUE TITLE
Large delays in SD Card Driver

### ISSUE THREAD

**Issue by granthaack** [kammce/SJSU-Dev2#444]
In the SD card driver at /library/L2_HAL/memory/sd.hpp there are very large hardcoded delays in the `ReadBlock()` function. These delays are passed in as parameters to the `SendCmd()` function. For example, line 699:

`SendCmd(read_cmd, address, sd.response.data.byte, 100, KeepAlive::kYes); //100ms delay`

There are a couple more examples peppered throughout the function. I've been able to shorten all of these down to around ~10ms and still get reliable SD card operation.

This isn't a bug, but I think it might make the MP3 project very difficult to complete. Data cannot be read fast enough from the SD card when the delays are in place, the song just starts and stops.

**Comment by ntwong0** [comment]
@kammce checking assignment

**Comment by rjavier441** [comment]
On It.
