### ISSUE TITLE
SSP Driver

### ISSUE THREAD

**Issue by kammce** [kammce/SJSU-Dev2#5]

**Comment by diarmadhi** [comment]
For the Integration testing section on the design doc, you made a comment about what I wrote is more application then proving it works on hardware. Then you comment that the Demonstration section you say that is were the application goes. 

So is it acceptable to move what's in integration to demonstration? I also did not think we'd being doing source code with the design doc, so hadn't included any previously.

**Comment by diarmadhi** [comment]
Also, most of what I can think of as "caveats" seem to fall under you comments about design choices. I'm not sure what would constitute a caveat in this driver.

**Comment by kammce** [comment]
These comments are not appropriate for this forum.
