### ISSUE TITLE
LTC4150 destructor should dettach gpio interrupt

### ISSUE THREAD

**Issue by kammce** [kammce/SJSU-Dev2#991]

**Comment by kammce** [comment]
@evanugarte Assigning this to you!

**Comment by kammce** [comment]
An alternative to this would be to utilize the HardwareCounter peripheral which will handle detaching the  gpio itself.

**Comment by evanugarte** [comment]
I wanted to abstract the `HardwareCounter` in `LTC4150` like so:
```cpp
  explicit constexpr Ltc4150(Gpio & int_pin,
                             Gpio & pol,
                             units::impedance::ohm_t resistance)
      : int_pin_(int_pin),
        pol_pin_(pol),
        resistance_(resistance),
        counter_(int_pin_, Gpio::Edge::kEdgeFalling), // instantiate hardwarecounter within the constructor
        pulses_(0),
        polarity_(Polarity::kDischarging)
  {
  }
```
this is proving to be difficult as I cannot find mock a constructor using FakeIt. Should I just instantiate the Hardware counter outside and make the constructor like below?

```cpp
explicit constexpr Ltc4150(HardwareCounter & int_pin,
                                          Gpio & pol,
                                          units::impedance::ohm_t resistance)
```

**Comment by kammce** [comment]
That can work, but I need to add the ability to count up and down. This is something that I've been working on, just haven't pushed it yet. I'll try and get it in.
